### ISSUE TITLE
Disable Namespacing

### ISSUE THREAD

**Issue by Gregoyle** [mrcrowl/vuex-typex#10]
Our application has its own namespacing setup with Vuex modules and I'm wondering if there is a way to skip namespacing in your setup?

**Comment by Gregoyle** [comment]
To clarify, we have fully qualified constants for all of our Vuex actions/mutations/etc. So that we don't need namespacing, as we have our own logic for setting the module name etc. I'd be happy to make a PR if you think it'd be possible and you could point at the right spot.

**Comment by ChristopherKiss** [comment]
@Gregoyle,

Do you mind posting an example of what you are trying to achieve?
