### ISSUE TITLE
System.register is not supported by webpack

### ISSUE THREAD

**Issue by mgdodge** [mrcrowl/vuex-typex#19]
Just updated the dependencies on a site template which includes vuex-typex. No problems before, but now getting the following:

```
warning  in ./node_modules/vuex-typex/dist/index.js
System.register is not supported by webpack.
```

**Comment by mrcrowl** [comment]
Ah shit.. sorry about that.  Switched back to commonjs output.

**Comment by mgdodge** [comment]
Updated 3.1.3 on npm is fixed, closing this issue. You might want to tag/update the releases on github to reflect the latest version on npm, it still says 3.0.1 is the latest release there.

**Comment by mrcrowl** [comment]
Thanks. Done.
