### ISSUE TITLE
Is it possible to dynamically register modules?

### ISSUE THREAD

**Issue by rugia813** [mrcrowl/vuex-typex#20]
tried to dynamically register modules for different pages, and got this error:
"Can't add module after vuexStore() has been called"

is this achievable somehow? register all modules for all pages doesn't seem to be ideal.

thanks

**Comment by mrcrowl** [comment]
:thinking: interesting... there's no _good_ reason why it shouldn't be possible.  Except that it hasn't been done.

**Comment by mrcrowl** [comment]
Thanks for the PR. I'll publish to npm when I'm back at a computer.

**Comment by mrcrowl** [comment]
Published as vuex-typex v3.1.5
