### ISSUE TITLE
Vue 2.5 and Vuex 3.0 support

### ISSUE THREAD

**Issue by eshimischi** [mrcrowl/vuex-typex#4]
Hi, amazing work here, but Vue / Vuex updated with new typescript "features". And your lib isnt compatible with it now.

**Comment by mrcrowl** [comment]
Hi @eshimischi, thanks for the heads up.  

Please try updating vuex-typex to v3.0.1 ---I figure it's going to be easier, long-term, to track along with vuex's own version numbers ¯\_(ツ)_/¯  

This update also requires: vuex 3.0.0, vue 2.5.0, typescript 2.5.0+

**Comment by eshimischi** [comment]
@mrcrowl thanks for response!
