### ISSUE TITLE
Nested module example

### ISSUE THREAD

**Issue by tmtk75** [mrcrowl/vuex-typex#5]
Could someone give an example for declaration using nested module?

**Comment by snovakovic** [comment]
@mrcrowl I'm also interesting to know is it possible to create submodule of the module?

`getStoreBuilder<IRootState>().module('testModule', initialState);`

Is there a way to creeate subModule module and apply it to testModule as a submodule?

And thanks for nice library!

**Comment by mrcrowl** [comment]
My apologies for delayed response here, I've been travelling.

See the nested test example here: https://github.com/mrcrowl/vuex-typex/blob/master/src/tests/nested.spec.ts

**Comment by mrcrowl** [comment]
You can call `.module(...)` from an existing module builder to create a sub module.

**Comment by tmtk75** [comment]
> You can call .module(...) from an existing module builder to create a sub module.

Got it. I didn't notice that. Thanks!
