### ISSUE TITLE
Not working with optional parameters

### ISSUE THREAD

**Issue by victorgarciaesgi** [mrcrowl/vuex-typex#7]
I have this mutation

```javascript
showLogin(state: ILoginState, route?: string)
```

But a payload is required when a call it!

**Comment by b12f** [comment]
Is this still an issue? I'm currently deciding how to handle vuex with TypeScript and a response from the devs would be helpful.

**Comment by victorgarciaesgi** [comment]
Yes still an issue for me...

**Comment by victorgarciaesgi** [comment]
See my repo (Moving Mate)[https://github.com/victorgarciaesgi/Moving-Mate?files=1]
I've implemented it and it's working well
