### ISSUE TITLE
Support request: usage with Nuxt

### ISSUE THREAD

**Issue by pkej** [mrcrowl/vuex-typex#8]
From your documentation it seems this is a pattern, and as such I can't find any export I can use in a plugins context in nuxt.config.js, and since I'm just starting out With TypeScript I have no clue, except looking at code from different repositories, and Learning TypeScriptl

I hope you can advise on how to use it with Nuxt.

**Comment by sobolevn** [comment]
The same here. Since I don't think that it is reasonable to use `typescript` without 100% type safety.
And I can clear see that `vuex` does not support typing out-of-the box.

Here's an example to demonstrate my point: 

```typescript
```

@pkej have you found any solution?

**Comment by mrcrowl** [comment]
Sorry folks, I have no experience with nuxt, so can't comment here.  

One option is to try and take this up with the author of [vuex-type-safety](https://www.npmjs.com/package/vuex-type-safety).  This guy forked from vuex-typex some time ago and may have an idea of how nuxt integrations could work.
