### ISSUE TITLE
Not an issue but of exemple of implementation in real project!

### ISSUE THREAD

**Issue by victorgarciaesgi** [mrcrowl/vuex-typex#9]
Link to the module declarations

[Module folder](https://github.com/victorgarciaesgi/Moving-Mate/tree/master/src/store/Modules);
[Store declaration](https://github.com/victorgarciaesgi/Moving-Mate/blob/master/src/store/Modules/Store/Store.ts)
[Store init](https://github.com/victorgarciaesgi/Moving-Mate/blob/master/src/App.vue)

[In component usage exemple](https://github.com/victorgarciaesgi/Moving-Mate/blob/master/src/components/components/Connexion.vue)

[Usage in other files exemple](https://github.com/victorgarciaesgi/Moving-Mate/blob/master/src/router/index.ts)

Hope it helps those who want to test this lib I really love it!

**Comment by Gregoyle** [comment]
I was looking through your code and one thing confused me. In your Global Store you type the context of your actions as ` async function fetchPaths(context: GlobalContext, svgPath: string) {` but in other modules you don't type the context in actions. Why do you, in that call, call `context.commit` rather than as you do in the other calls, to `Mutations.mutations.someCall`?

**Comment by victorgarciaesgi** [comment]
@Gregoyle Hi! Thanks for looking into it. I struggled myself to put this in place so I understand that you have problems emulating it !
For the GlobalStore that was an old context commit I forgot to change, If you look into LoginStore for exemple you will see I always use `Mutations.mutations.someCall`. But i think you just need to put the parameter in place so the typings works. 
That was a choice of myself to use namespaces like this and I don't know if it's good practice so if you find a better and proper solution don't forget to notify me! :)
Also if you have other questions on my code I'm here

**Comment by Gregoyle** [comment]
@victorgarciaesgi 

Hi Victor, I'm wondernig if you ever ran into this issue?
https://github.com/mrcrowl/vuex-typex/issues/11
